stages:
  - deploy

pages:
  stage: deploy
  image: python:3.9
  script:
    - pip install mkdocs mkdocs-material
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  only:
    - main

