site_name: MkDocs Bootstrap Theme
site_url: https://ntubmlab.github.io/NTUBMLab_Wiki/

repo_url: https://ntubmlab.github.io/NTUBMLab_Wiki/

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, <a href="http://www.dougalmatthews.com/">Dougal Matthews</a>.

theme:
    name: bootstrap

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-jupyter
