site_name: MkDocs Bootstrap Theme
site_url: https://ntubmlab.github.io/NTUBMLab_Wiki/
site_description: Ntubmlab Webwiki Bootstrap Theme
site_author: William(here to suffer)

repo_url: https://ntubmlab.github.io/NTUBMLab_Wiki/


theme:
    name: bootstrap

nav:
    - Home: index.md

plugins:
    - search
